//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.18 at 05:40:07 PM EET 
//


package org.example;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Movie_QNAME = new QName("", "Movie");
    private final static QName _MovieLength_QNAME = new QName("", "movieLength");
    private final static QName _LastName_QNAME = new QName("", "lastName");
    private final static QName _CategoryName2_QNAME = new QName("", "categoryName2");
    private final static QName _Actor_QNAME = new QName("", "Actor");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _Producer_QNAME = new QName("", "producer");
    private final static QName _Actors_QNAME = new QName("", "Actors");
    private final static QName _LanguageName2_QNAME = new QName("", "languageName2");
    private final static QName _CategoryName_QNAME = new QName("", "categoryName");
    private final static QName _LanguageName_QNAME = new QName("", "languageName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MovieType }
     * 
     */
    public MovieType createMovieType() {
        return new MovieType();
    }

    /**
     * Create an instance of {@link ActorType }
     * 
     */
    public ActorType createActorType() {
        return new ActorType();
    }

    /**
     * Create an instance of {@link ProducerType }
     * 
     */
    public ProducerType createProducerType() {
        return new ProducerType();
    }

    /**
     * Create an instance of {@link ActorsType }
     * 
     */
    public ActorsType createActorsType() {
        return new ActorsType();
    }

    /**
     * Create an instance of {@link CategoryNameType }
     * 
     */
    public CategoryNameType createCategoryNameType() {
        return new CategoryNameType();
    }

    /**
     * Create an instance of {@link LanguageNameType }
     * 
     */
    public LanguageNameType createLanguageNameType() {
        return new LanguageNameType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MovieType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Movie")
    public JAXBElement<MovieType> createMovie(MovieType value) {
        return new JAXBElement<MovieType>(_Movie_QNAME, MovieType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "movieLength")
    public JAXBElement<String> createMovieLength(String value) {
        return new JAXBElement<String>(_MovieLength_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lastName")
    public JAXBElement<String> createLastName(String value) {
        return new JAXBElement<String>(_LastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "categoryName2")
    public JAXBElement<String> createCategoryName2(String value) {
        return new JAXBElement<String>(_CategoryName2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Actor")
    public JAXBElement<ActorType> createActor(ActorType value) {
        return new JAXBElement<ActorType>(_Actor_QNAME, ActorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProducerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "producer")
    public JAXBElement<ProducerType> createProducer(ProducerType value) {
        return new JAXBElement<ProducerType>(_Producer_QNAME, ProducerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActorsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Actors")
    public JAXBElement<ActorsType> createActors(ActorsType value) {
        return new JAXBElement<ActorsType>(_Actors_QNAME, ActorsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "languageName2")
    public JAXBElement<String> createLanguageName2(String value) {
        return new JAXBElement<String>(_LanguageName2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CategoryNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "categoryName")
    public JAXBElement<CategoryNameType> createCategoryName(CategoryNameType value) {
        return new JAXBElement<CategoryNameType>(_CategoryName_QNAME, CategoryNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "languageName")
    public JAXBElement<LanguageNameType> createLanguageName(LanguageNameType value) {
        return new JAXBElement<LanguageNameType>(_LanguageName_QNAME, LanguageNameType.class, null, value);
    }

}
